CrawlerWebApp/Controllers/SearchProductController.cs
using CrawlerEngine.Common.Extansion;
using CrawlerEngine.Models;
using CrawlerEngine.Repository.Factory;
using HtmlAgilityPack;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using static CrawlerEngine.Common.Enums.ElectronicBusiness;

namespace CrawlerWebApp.Controllers
{
    public class SearchProductController : Controller
    {
        public SearchProductController()
        {
            crawlFactory = new CrawlFactory("POSTGRESSQL");
        }


        private CrawlFactory crawlFactory;
        // GET: SearchProduct
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetFeeBeeData([FromBody] FeeBeeRequest data)
        {
            return Json(GetDataFromFeebee(data.product));
            //var response = crawlFactory.CrawlDataJobListRepository.GetCrawlDataJobDiffStatus();
            //return Json(response);
        }
        [HttpPost]
        public IActionResult sendFeeBeeDataToJob([FromBody] FeeBeeStruct data)
        {
            try
            {
                JobInfo jobInfo = new JobInfo();
                jobInfo.Url = data.href;
                jobInfo.JobType = GetJobType(data);
                jobInfo.PutToDic("_title", data.title);
                jobInfo.PutToDic("_price", data.data_price);
                if (string.IsNullOrEmpty(jobInfo.JobType)) return Json(new ReturnMessage<object>
                {
                    success = false,
                    returnMsg = "No Provider"
                });
                crawlFactory.CrawlDataJobListRepository.InsertOne(jobInfo, jobInfo.JobType);
                return Json(new ReturnMessage<object>
                {
                    success = true,
                    returnMsg = data.title + "  新增成功"
                });
            }
            catch (Exception ex)
            {

                return Json(new ReturnMessage<object>
                {
                    success = false,
                    returnMsg = ex.Message + ex.StackTrace
                });
            }


        }


        [HttpPost]
        public IActionResult sendAllFeeBeeDataToJob([FromBody] List<SelectFeeBeeStruct> datas)
        {
            try
            {

                JobInfo jobInfo = new JobInfo();
                foreach (var data in datas.Where(x => x.selected))
                {
                    jobInfo.Url = data.href;
                    jobInfo.JobType = GetJobType(data);
                    jobInfo.PutToDic("_title", data.title);
                    jobInfo.PutToDic("_price", data.data_price);
                    if (string.IsNullOrEmpty(jobInfo.JobType)) return Json(new ReturnMessage<object>
                    {
                        success = false,
                        returnMsg = "No Provider"
                    });
                    crawlFactory.CrawlDataJobListRepository.InsertOne(jobInfo, jobInfo.JobType);
                }
                return Json(new ReturnMessage<object>
                {
                    success = true,
                    returnMsg = " 新增成功"
                });
            }
            catch (Exception ex)
            {

                return Json(new ReturnMessage<object>
                {
                    success = false,
                    returnMsg = ex.Message + ex.StackTrace
                });
            }


        }

        private List<FeeBeeStruct> GetDataFromFeebee(string product)
        {
            var httpClient = new HttpClient();
            var targetUrl = $"https://feebee.com.tw/s/?q={product}";
            var httpResponse = httpClient.GetAsync(targetUrl).GetAwaiter().GetResult();


            HtmlDocument htmlDoc = new HtmlDocument();
            htmlDoc.LoadHtml(httpResponse.Content.ReadAsStringAsync().GetAwaiter().GetResult());
            var cc = htmlDoc.DocumentNode.SelectNodes("//*[@id=\"list_view\"]/li/span[2]/a");
            List<FeeBeeStruct> la = new List<FeeBeeStruct>();
            FeeBeeStruct a = new FeeBeeStruct();
            foreach (var data in cc)
            {
                a = new FeeBeeStruct();
                a.href = data.GetAttributes("href").FirstOrDefault().Value.Replace("&amp;", "&");
                a.data_store = data.GetAttributes("data-store").FirstOrDefault()?.Value;
                a.data_price = data.GetAttributes("data-price").FirstOrDefault().Value;
                a.data_provider = data.GetAttributes("data-provider").FirstOrDefault().Value;
                a.title = data.GetAttributes("title").FirstOrDefault().Value;

                la.Add(a);
            }
            return la;
            // File.WriteAllText("testfeebee.txt", JsonConvert.SerializeObject(la));
        }
        private string GetJobType(FeeBeeStruct data)
        {
            string returnStr = string.Empty;
            if (data.data_provider.ToLower() == "momoshop")
            {
                returnStr = Platform.MomoShopProduct.GetDescription();
            }
            if (data.data_provider.ToLower() == "24hpchome")
            {
                returnStr = Platform.Pchome24hProduct.GetDescription();
            }
            if (data.data_provider.ToLower() == "ybuy")
            {
                returnStr = Platform.YahooBuyProduct.GetDescription();
            }
            if (data.data_provider.ToLower() == "jollybuy")
            {
            }
            if (data.data_provider.ToLower() == "etmall")
            {
                returnStr = Platform.ETMallProduct.GetDescription();

            }
            if (data.data_provider.ToLower() == "umall")
            {
            }
            if (data.data_provider.ToLower() == "spstore")
            {
            }

            return returnStr;
        }
        public class ReturnMessage<T>
        {
            public bool success { get; set; }
            public string returnMsg { get; set; }
            public T data { get; set; }
        }
        public class FeeBeeRequest
        {
            public string product { get; set; }
        }
        public class FeeBeeStruct
        {
            public string href { get; set; }
            public string data_store { get; set; }
            public string data_price { get; set; }
            public string data_provider { get; set; }
            public string title { get; set; }
        }
        public class SelectFeeBeeStruct : FeeBeeStruct
        {

            public bool selected { get; set; }
        }


    }
}

CrawlerWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link data-require="bootstrap@3.3.7" data-semver="3.3.7" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link data-require="bootstrap-css@3.*" data-semver="3.3.7" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css" />
    <script data-require="angular.js@1.6.5" data-semver="1.6.5" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js"></script>
    <script data-require="angular-animate@1.6.*" data-semver="1.6.5" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular-animate.min.js"></script>
    <script data-require="angular-touch@1.6.*" data-semver="1.6.2" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.2/angular-touch.js"></script>
    <script data-require="ui-bootstrap" data-semver="2.5.0" src="https://cdn.rawgit.com/angular-ui/bootstrap/gh-pages/ui-bootstrap-tpls-2.5.0.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">爬爬爬怎樣都爬不死</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Panel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SearchProduct" asp-action="Index">SearchProduct</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CrawlerWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>